// One-off: convert the fixtures in src/forms to coded options (@yourco/forms
// 0.18.0, contract §13). Plain-string option lists become { code, label },
// with codes generated by the builder's rule (§13.3), and every condition on a
// coded source has its answer turned from the label into the code.
//
// Usage: node scripts/convert-options.mjs [--check]
//   --check  verifies the generator against the §13.3 table and stops.
//
// Safe to run twice: lists that are already coded keep their codes, and only
// empty codes are generated, as the builder does.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const FORMS_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'forms');
const MAX = 64;
const SINGLE = new Set(['choice', 'dropdown']);
const MULTI = new Set(['checkbox', 'multiselect', 'ranking']);
const CODED = new Set([...SINGLE, ...MULTI, 'matrix']);

// ---------------------------------------------------------------- §13.3

const trimPunctuation = (text) => text.replace(/^[._-]+|[._-]+$/g, '');

/** Steps 1–5: the label's own candidate code, possibly empty. */
function baseCode(label) {
  let text = label.normalize('NFKD').replace(/\p{M}/gu, ''); // 1. NFKD, accents off
  text = text.toLowerCase(); // 2
  text = text.replace(/\s+/g, '_'); // 3
  text = text.replace(/[^a-z0-9._-]/g, '').replace(/_+/g, '_'); // 4
  text = trimPunctuation(text).slice(0, MAX); // 5
  return trimPunctuation(text);
}

/**
 * Codes for one list, in list order. `existing` holds codes already present
 * (typed or saved), reserved first; only entries without a code are generated.
 */
function generateCodes(labels, existing = labels.map(() => '')) {
  const taken = new Set(existing.filter(Boolean).map((code) => code.toLowerCase()));
  return labels.map((label, index) => {
    if (existing[index]) return existing[index];
    const base = baseCode(label) || `option_${index + 1}`; // 6
    let code = base;
    for (let n = 2; taken.has(code.toLowerCase()); n += 1) {
      // 7. Append _2, _3, …, shortening the base to stay within 64.
      const suffix = `_${n}`;
      code = base.slice(0, MAX - suffix.length) + suffix;
    }
    taken.add(code.toLowerCase());
    return code;
  });
}

/** The §13.3 table, row by row, each in the list context it describes. */
function checkTable() {
  const rows = [
    [['Not applicable'], 0, 'not_applicable'],
    [['Married, separated'], 0, 'married_separated'],
    [['Sí'], 0, 'si'],
    [['F32.1 Major depressive disorder'], 0, 'f32.1_major_depressive_disorder'],
    [['--Yes--'], 0, 'yes'],
    [['<script>alert(1)</script>'], 0, 'scriptalert1script'],
    [['First', 'Second', '焦虑'], 2, 'option_3'],
  ];
  const failures = [];
  for (const [labels, index, expected] of rows) {
    const actual = generateCodes(labels)[index];
    if (actual !== expected) failures.push(`${JSON.stringify(labels[index])}: got ${actual}, expected ${expected}`);
  }
  // `Other!` when `other` is already a code.
  const other = generateCodes(['Other', 'Other!'], ['other', ''])[1];
  if (other !== 'other_2') failures.push(`"Other!": got ${other}, expected other_2`);
  // Not in the table, but part of the rule: the suffix keeps the whole within 64.
  const long = generateCodes(['a'.repeat(70), 'A'.repeat(70)]);
  if (long[1] !== `${'a'.repeat(62)}_2` || long[1].length !== 64) failures.push(`64-character collision: got ${long[1]}`);
  return failures;
}

// ---------------------------------------------------------------- fixtures

/** A list of strings or partial options as { code, label }, generating empty codes. */
function codedList(list, where) {
  if (!Array.isArray(list)) throw new Error(`${where}: not a list`);
  const labels = list.map((entry) => (typeof entry === 'string' ? entry : entry.label));
  const existing = list.map((entry) => (typeof entry === 'string' ? '' : entry.code ?? ''));
  const codes = generateCodes(labels, existing);
  return labels.map((label, index) => ({ code: codes[index], label }));
}

function* walk(blocks) {
  for (const block of blocks) {
    yield block;
    if (Array.isArray(block.blocks)) yield* walk(block.blocks);
  }
}

function convertSchema(schema, file) {
  const blocks = [...walk(schema.blocks)];
  const byId = new Map(blocks.map((block) => [block.id, block]));
  const changes = { lists: 0, conditions: 0 };

  for (const block of blocks) {
    if (!CODED.has(block.type)) continue;
    if (block.options !== undefined) {
      const before = JSON.stringify(block.options);
      block.options = codedList(block.options, `${file} ${block.id} options`);
      if (JSON.stringify(block.options) !== before) changes.lists += 1;
    }
    if (block.type === 'matrix' && block.columns !== undefined) {
      const before = JSON.stringify(block.columns);
      block.columns = codedList(block.columns, `${file} ${block.id} columns`);
      if (JSON.stringify(block.columns) !== before) changes.lists += 1;
    }
  }

  for (const block of blocks) {
    for (const condition of block.enableWhen ?? []) {
      const source = byId.get(condition.question);
      if (!source || !(SINGLE.has(source.type) || MULTI.has(source.type)) || !('answer' in condition)) continue;
      const options = source.options ?? [];
      if (options.some((option) => option.code === condition.answer)) continue; // already a code
      const match = options.find((option) => option.label === condition.answer);
      if (!match) {
        throw new Error(`${file}: ${block.id} has a condition on ${source.id} whose answer ${JSON.stringify(condition.answer)} is neither a label nor a code of its list`);
      }
      condition.answer = match.code;
      changes.conditions += 1;
    }
  }
  return changes;
}

// ---------------------------------------------------------------- main

const failures = checkTable();
if (failures.length > 0) {
  console.error('The generator does not match the §13.3 table:\n  ' + failures.join('\n  '));
  process.exit(1);
}
console.log('§13.3 table: all rows match.');
if (process.argv.includes('--check')) process.exit(0);

for (const file of readdirSync(FORMS_DIR).filter((name) => name.endsWith('.json')).sort()) {
  const path = resolve(FORMS_DIR, file);
  const schema = JSON.parse(readFileSync(path, 'utf8'));
  const changes = convertSchema(schema, file);
  if (changes.lists === 0 && changes.conditions === 0) {
    console.log(`${file}: nothing to convert`);
    continue;
  }
  writeFileSync(path, JSON.stringify(schema, null, 2) + '\n');
  console.log(`${file}: ${changes.lists} list(s), ${changes.conditions} condition(s)`);
}
